version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/balloon/invite
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          key: mod-{{ checksum "go.sum" }}
      - run:
          name: install dependencies
          command: go get
      - run:
          name: unit test
          command: go test -v ./...
      - save_cache:
          key: mod-{{ checksum "go.sum" }}
          paths:
            - $GOPATH/pkg/mod
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: gcloud configuration
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: deploy create invitation
          command:
            gcloud functions deploy create-invitation --region asia-northeast1 --entry-point CreateInvitation --runtime go113 --trigger-http
      - run:
          name: deploy invitation-topic
          command:
            gcloud functions deploy invitation-topic --region asia-northeast1 --entry-point GetTopicId --runtime go113 --trigger-http
      - run:
          name: deploy invitation-code
          command:
            gcloud functions deploy invitation-code --region asia-northeast1 --entry-point GetInvitationCode --runtime go113 --trigger-http
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy
